// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcRxvy3wtGCvWv2Dr5Gp5i899Gf-8Nzg',
    appId: '1:603638923079:web:0e90f416c05c832fa39662',
    messagingSenderId: '603638923079',
    projectId: 'jelajah-firebase-49527',
    authDomain: 'jelajah-firebase-49527.firebaseapp.com',
    storageBucket: 'jelajah-firebase-49527.firebasestorage.app',
    measurementId: 'G-Y945H0RQT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIlftb0yrNKz1VjsHihPPoTA6i4vIY5Ug',
    appId: '1:603638923079:android:4293bbde199e358fa39662',
    messagingSenderId: '603638923079',
    projectId: 'jelajah-firebase-49527',
    storageBucket: 'jelajah-firebase-49527.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKcRxvy3wtGCvWv2Dr5Gp5i899Gf-8Nzg',
    appId: '1:603638923079:web:f31c71e92f846361a39662',
    messagingSenderId: '603638923079',
    projectId: 'jelajah-firebase-49527',
    authDomain: 'jelajah-firebase-49527.firebaseapp.com',
    storageBucket: 'jelajah-firebase-49527.firebasestorage.app',
    measurementId: 'G-6B83QTS0EW',
  );
}
